data-dir: tmp/data/
device: cpu

lexicon-path: kaldi/data/lexicon

nnet3:
  num_senones: 6128
  conf-path: kaldi/conf
  kaldi-chain-mdl-path: kaldi/exp/chain_cleaned/tdnn_1d_sp/final.mdl
  transition-model-path: kaldi/exp/chain_cleaned/tdnn_1d_sp/final.mdl
  tree-path: kaldi/exp/chain_cleaned/tdnn_1d_sp/tree
  kaldi-phones-path: kaldi/exp/chain_cleaned/tdnn_1d_sp/phones.txt

data:
  disambig-path: kaldi/data/lang_test_tgsmall/phones/disambig.int
  word-boundary-path: kaldi/data/lang_test_tgsmall/phones/word_boundary.int
  lang-graph-path: kaldi/data/lang_test_tgsmall/L.fst
  words-path: kaldi/data/lang_test_tgsmall/words.txt

gmm:
  conf-path: kaldi/conf
  kaldi-gmm-mdl-path: kaldi/exp/tri6b/final.alimdl
  kaldi-mat-matrix-path: kaldi/exp/tri6b/final.mat
  tree-path: kaldi/exp/tri6b/tree
  phones-path: kaldi/exp/tri6b/phones.txt

acoustic-model-path: kaldi/torch/acoustic_model.pt