# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
wav2vec2_hub: "microsoft/wavlm-large"

# Data files
wav2vec2_save_path: pretrained
label_encoder_path: results/scoring/save/label_encoder.txt
lexicon_path: lexicon
ckpt_path: results/scoring/save/best

# Relative Position Id
PAD_POSITION_ID: 0
START_POSITION_ID: 1
INNER_POSITION_ID: 2
END_POSITION_ID: 3

number_of_epochs: 10
batch_size: 16
lr: 0.0003
sample_rate: 16000
device: cuda

# Model parameters
activation: !name:torch.nn.LeakyReLU
dnn_layers: 2
dec_layers: 1
dnn_neurons: 1024
emb_size: 128
dec_neurons: 256
dec_attn_dim: 256
scorer_dnn_blocks: 1
scorer_dnn_neurons: 1024
freeze_wav2vec: False
scorer_similarity_dnn_blocks: 1
scorer_similarity_dnn_neurons: 512
similarity_calc: "cosine"  # The type of similarity computation to use. Allowable values: "cosine", "euclidean", "nn".

# 45
num_phones: 45
output_neurons: 45 # 39phs+sil+blank+eos+bos
bos_index: 0
eos_index: 1
blank_index: 2

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 16

# Optimization
ckpt_enable: true
trial_id: None

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

valid_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    save_path: !ref <wav2vec2_save_path>
    output_norm: True
    freeze: !ref <freeze_wav2vec>

enc: !new:speechbrain.lobes.models.VanillaNN.VanillaNN
    input_shape: [null, null, 1024]
    activation: !ref <activation>
    dnn_blocks: !ref <dnn_layers>
    dnn_neurons: !ref <dnn_neurons>

emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

emb_scorer: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <num_phones>
    embedding_dim: !ref <dec_neurons>

dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: !ref <dnn_neurons>
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: !ref <dec_neurons>
    attn_dim: !ref <dec_attn_dim>
    num_layers: !ref <dec_layers>
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dec_neurons>
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

seq_cost: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.1

score_cost: !name:speechbrain.nnet.losses.mse_loss
pcc: !name:torch.corrcoef

scorer_nn: !new:speechbrain.nnet.containers.Sequential
    input_shape: [null, null, !ref <dec_neurons>]
    model: !new:speechbrain.lobes.models.VanillaNN.VanillaNN
        input_shape: [null, null, !ref <dec_neurons>]
        dnn_blocks: !ref <scorer_dnn_blocks>
        dnn_neurons: !ref <scorer_dnn_neurons>
        activation: !ref <activation>
    bn1: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation_final: !new:torch.nn.ReLU

scorer_similarity_nn: !new:speechbrain.nnet.containers.Sequential
    input_shape: [ null, null, !ref <scorer_dnn_neurons> * 2 ]
    model: !new:speechbrain.lobes.models.VanillaNN.VanillaNN
        input_shape: [ null, null, !ref <scorer_dnn_neurons> * 2 ]
        dnn_blocks: !ref <scorer_similarity_dnn_blocks>
        dnn_neurons: !ref <scorer_similarity_dnn_neurons>
        activation: !ref <activation>
    bn1: !name:speechbrain.nnet.normalization.BatchNorm1d
    linear: !new:speechbrain.nnet.linear.Linear
        input_size: !ref <scorer_similarity_dnn_neurons>
        n_neurons: 1
    activation_final: !new:torch.nn.Hardtanh
        min_val: 0.0
        max_val: 1.0

greedy_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNGreedySearcher
    embedding: !ref <emb>
    decoder: !ref <dec>
    linear: !ref <seq_lin>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>

beam_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNBeamSearcher
    embedding: !ref <emb>
    decoder: !ref <dec>
    linear: !ref <seq_lin>
    ctc_linear: !ref <ctc_lin>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    blank_index: !ref <blank_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <beam_size>

model: !new:torch.nn.ModuleList
    - [!ref <enc>, !ref <emb>, !ref <dec>, !ref <ctc_lin>, !ref <seq_lin>]

model_scorer: !new:torch.nn.ModuleList
    - [!ref <scorer_nn>, !ref <emb_scorer>, !ref <scorer_similarity_nn>, !ref <prep_scorer>]

prep_scorer: !new:src.model.prep_model.PrepModel
    embed_dim: 32
    num_heads: 1
    depth: 3
    input_dim: 256
    max_length: 256
    dropout: 0.1
    num_phone: 46
    
modules:
    wav2vec2: !ref <wav2vec2>
    prep_scorer: !ref <prep_scorer>
    enc: !ref <enc>
    emb: !ref <emb>
    dec: !ref <dec>
    ctc_lin: !ref <ctc_lin>
    seq_lin: !ref <seq_lin>
    scorer_nn: !ref <scorer_nn>
    emb_scorer: !ref <emb_scorer>
    scorer_similarity_nn: !ref <scorer_similarity_nn>
